name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Copy pre-built projects
      run: |
        # Create main deployment directory
        mkdir -p dist

        # Copy each React project (assuming they're already built)
        for project_dir in calculator tic-tac-toe todo-list-manager; do
          if [ -d "$project_dir" ]; then
            echo "Copying $project_dir..."

            # Copy the entire project directory to dist
            cp -r "$project_dir" "dist/$project_dir"
          else
            echo "Warning: $project_dir directory not found"
          fi
        done

    - name: Create index page
      run: |
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>React Projects</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 2rem;
                    background: #f5f5f5;
                }
                .container {
                    background: white;
                    padding: 2rem;
                    border-radius: 8px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                }
                h1 {
                    color: #333;
                    text-align: center;
                    margin-bottom: 2rem;
                }
                .projects {
                    display: grid;
                    gap: 1rem;
                    margin-top: 2rem;
                }
                .project-card {
                    border: 1px solid #ddd;
                    border-radius: 6px;
                    padding: 1.5rem;
                    text-decoration: none;
                    color: inherit;
                    transition: transform 0.2s, box-shadow 0.2s;
                }
                .project-card:hover {
                    transform: translateY(-2px);
                    box-shadow: 0 4px 20px rgba(0,0,0,0.15);
                }
                .project-title {
                    font-size: 1.25rem;
                    font-weight: 600;
                    margin-bottom: 0.5rem;
                    color: #0066cc;
                }
                .project-description {
                    color: #666;
                    line-height: 1.5;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>React Projects</h1>
                <p>Select a project to view:</p>
                <div class="projects">
                    <a href="./calculator/" class="project-card">
                        <div class="project-title">Calculator</div>
                        <div class="project-description">A React-based calculator application</div>
                    </a>
                    <a href="./tic-tac-toe/" class="project-card">
                        <div class="project-title">Tic-Tac-Toe</div>
                        <div class="project-description">Classic tic-tac-toe game built with React</div>
                    </a>
                    <a href="./todo-list-manager/" class="project-card">
                        <div class="project-title">Todo List Manager</div>
                        <div class="project-description">A task management app for organizing your todos</div>
                    </a>
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4